name: Compile library items
on: [push]
jobs:
  compile-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Merge library configuration
        run: go run ./compile.go
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::v$(date +"%Y-%m-%d.%H-%M")"
      - name: Release library configuration
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: dist/library.json
